[ADD] 초기 환경 세팅
wecode-bootcamp-korea/36-1st-Team-Corner-backend pull request #1
Opened 2022-08-16 09:24 UTC by LeeJ1Hyun

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 초기 환경 세팅
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 프로젝트를 위한 초기 환경 세팅 구성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- .env, .env.sample 생성
- .gitignore 생성
- app.js 생성
- package.json 생성 (cors, dotenv, express, morgan, nodemon, typeorm, dbmate dependencies 추가)

![initial-setting](https://user-images.githubusercontent.com/100523786/184845613-4694b038-da5a-4714-acda-7da1728b9582.png)
- 초기 환경 세팅 구조

<br />

2022-08-16 09:45 UTC, bigfanoftim requested changes

2022-08-16 09:45 UTC, bigfanoftim commented on package.json
> +    "morgan": "^1.10.0",
morgan은 devDependancy가 아니라 위에 올려야 할 것 같습니다.

2022-08-16 10:39 UTC, LeeJ1Hyun commented on package.json
> +    "morgan": "^1.10.0",
리뷰 확인 후 수정했습니다.

2022-08-17 01:53 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-17 01:53 UTC, merged