장바구니 정보 조회 기능 추가
wecode-bootcamp-korea/36-1st-Team-Corner-backend pull request #10
Opened 2022-08-24 06:20 UTC by sk8ilar

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

장바구니 기능 (get) 추가
유저가 장바구니를 볼때 자신이 선택한 모든 장바구니를 조회할 수 있는 기능을 추가했습니다.

<br />

2022-08-24 06:40 UTC, bigfanoftim requested changes

2022-08-24 06:40 UTC, bigfanoftim commented on routes/cartRouter.js
> +router.get("/user", auth.validationToken, cartController.selectAllCart);
```suggestion
router.get("", auth.validationToken, cartController.selectAllCart);
```

2022-08-24 06:40 UTC, bigfanoftim commented on routes/index.js
> +router.use("/cart", cartRouter.router)
```suggestion
router.use("/carts", cartRouter.router)
```
endpoint 주소가 `:3000/carts`만 되어도 충분할 것 같아요.

2022-08-24 06:40 UTC, bigfanoftim commented on controllers/cartController.js
> +const selectAllCart = async (req, res) => {
```suggestion
const getCarts = async (req, res) => {
```
네이밍이 너무 복잡합니다. 그냥 데이터를 가져오는 것이면 get으로 충분할 것 같습니다.
이에 맞게 전부 수정해 주세요.

2022-08-24 06:40 UTC, bigfanoftim commented on services/cartService.js
> +const selectAllCart = async (userId) => {
지금보니 어디는 select고 어디는 get이네요. get으로 통일해 주세요.

2022-08-24 06:40 UTC, bigfanoftim commented on models/cartDao.js
> +        `
결과가 의도하신대로 잘 나오던가요?

2022-08-24 07:21 UTC, sk8ilar commented on models/cartDao.js
> +        `
제가 개인적으로 해봤을 때 기능적인 문제는 일단 없어서 올렸습니다! 혹시 어떤 점 때문에 그러는지 알 수 있을까요?

2022-08-24 12:56 UTC, bigfanoftim requested changes
간단한 수정사항입니다. 나머진 👍

2022-08-24 12:56 UTC, bigfanoftim commented on models/cartDao.js
> +    }
- 이렇게 try catch를 써버리면 syntaxerror도 프로덕트가 존재하지 않는다는 에러를 반환할 거 같은데 다시 고려해야 할 것 같아요.
```JavaScript
const result = AppDataSource.query(`
  SELECT *
  FROM ..
`)

if (..) {
  err..
}
```
이런 느낌으로 가야합니다.

2022-08-25 02:41 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-25 02:41 UTC, merged