ADD: 상품 정보 조회기능 추가
wecode-bootcamp-korea/36-1st-Team-Corner-backend pull request #7
Opened 2022-08-20 12:55 UTC by sk8ilar

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. (main page) get메서드와 쿼리 파라미터를 이용하여 전체 상품을 불러오지만 9개씩 끊어서 불러올 수 있게 만들었습니다.
2.(카테고리) 마찬가지로 get메서드와 쿼리 파라미터를 이용하여 카테고리에 맞는 상품들을 불러올 수 있도록 기능 구현했습니다.
3.(검색 기능) get메서드와 쿼리 파라미터를 이용하여 검색한 단어와 관련된 이름을 가지고 있는 상품들을 불러올 수 있는 기능을 구현했습니다.
4. (상품 상세 페이지) get메서드를 이용하여 상품 상세 페이지에서 상품하나와 관련된 정보를 불러 올 수 있는 기능을 구현했습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-08-22 10:31 UTC, bigfanoftim requested changes
`productsController.js` 와 `oneProductController.js`는 어차피 하나의 product 데이터를 다루는 controller이니 하나로 통일해주세요.

2022-08-22 10:32 UTC, bigfanoftim requested changes
추가로 mainDao를 만드셨는데, 클라이언트에서 처리해야 할 일인 페이징에 관여하지 마시고 다루는 데이터에 집중해 주세요.

2022-08-23 00:43 UTC, sk8ilar commented
멘토님! mainController, mainService, mainDao는 사실 원래 없었으나 productRouter에서 main페이지의 기능을 수행하지 못하면서(/product/list) 따로 상품이 싼 목록 9개를 대표 상품으로 메인페이지를 만들자는 생각에 main이라는 분기를 만들었습니다! 혹시 이 부분에 대해서는 2시쯤에 어떻게 해야할지 따로 여쭤봐도 될까요?

2022-08-23 03:14 UTC, bigfanoftim commented
> 멘토님! mainController, mainService, mainDao는 사실 원래 없었으나 productRouter에서 main페이지의 기능을 수행하지 못하면서(/product/list) 따로 상품이 싼 목록 9개를 대표 상품으로 메인페이지를 만들자는 생각에 main이라는 분기를 만들었습니다! 혹시 이 부분에 대해서는 2시쯤에 어떻게 해야할지 따로 여쭤봐도 될까요?

넵!

2022-08-24 04:22 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-24 04:26 UTC, merged