[ADD] 제품 상세페이지 장바구니 담기, 조회 기능 구현
wecode-bootcamp-korea/36-1st-Team-Corner-backend pull request #8
Opened 2022-08-23 08:07 UTC by LeeJ1Hyun

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상세 페이지 내 장바구니 담기, 유저의 장바구니 내 상품 갯수 조회 기능

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 제품 상세페이지 내 장바구니 담기
- 입력되는 값을 유효성 검사 후 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현
- 재고보다 요청값이 크게 될 경우 에러 메시지를 반환 예외 처리 구현
- 장바구니에 요청값과 상품 아이디를 DB에 INSERT 구현
- 존재하는 상품일 경우 quantity만을 DB에 UPDATE 구현

2. 유저의 장바구니 갯수 조회
- jwt를 복호화하여 유저 Id에 따라 장바구니에 담긴 상품의 갯수를 반환하는 기능 구현 (상단바 뱃지용) 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 이미 장바구니에 존재하는 상품에 대한 수량을 늘리는 로직을 이해하게 되었다.

<br />

2022-08-24 05:02 UTC, bigfanoftim requested changes

2022-08-24 05:02 UTC, bigfanoftim commented on services/cartService.js
> +    err.statusCode = 401;
```suggestion
    err.statusCode = 400;
```
401 보다는 400이 더 괜찮아보이네요~

2022-08-24 14:55 UTC, LeeJ1Hyun commented on services/cartService.js
> +    err.statusCode = 401;
네 리뷰 사항 반영했습니다. 400코드!

2022-08-25 02:00 UTC, bigfanoftim approved these changes
LGTM 👍

2022-08-25 02:00 UTC, merged